using RecruiterCRM.classes.Views.Helpers;
using RecruiterCRM.classes.Views;
using RecruiterCRM.classes;
using ConsoleFramework;
using ConsoleFramework.Controls;

namespace RecruiterCRM.forms
{
    /*
     *  GENERATED BY A YET-TO-BE-RELEASED CONSOLE EDITOR
     */
    [CRMFormTemplate("companies-list")]
    public partial class CompaniesList
    {
        public CompaniesList(CRM crm, CRMFormLanguage lang) : base(crm, lang) { }
        /*
         *  CONTROLS
         */
        private ListBox _lstCompanies = null;
        public ListBox lstCompanies
        {
            get { return _lstCompanies ?? (_lstCompanies = HWND.FindChildByName<ListBox>("lstCompanies")); }
            set { _lstCompanies = value; }
        }
        private Panel _pnlCompany = null;
        public Panel pnlCompany
        {
            get { return _pnlCompany ?? (_pnlCompany = HWND.FindChildByName<Panel>("pnlCompany")); }
            set { _pnlCompany = value; }
        }
        private ListBox _lstCompRecruiters = null;
        public ListBox lstCompRecruiters
        {
            get { return _lstCompRecruiters ?? (_lstCompRecruiters = pnlCompany.FindChildByName<ListBox>("lstRecruiters")); }
            set { _lstCompRecruiters = value; }
        }
        private TextBox _txtCompName = null;
        public TextBox txtCompName
        {
            get { return _txtCompName ?? (_txtCompName = pnlCompany.FindChildByName<TextBox>("txtName")); }
            set { _txtCompName = value; }
        }
        private TextBox _txtCompWebsite = null;
        public TextBox txtCompWebsite
        {
            get { return _txtCompWebsite ?? (_txtCompWebsite = pnlCompany.FindChildByName<TextBox>("txtWebsite")); }
            set { _txtCompWebsite = value; }
        }
        private TextBox _txtCompNotes = null;
        public TextBox txtCompNotes
        {
            get { return _txtCompNotes ?? (_txtCompNotes = pnlCompany.FindChildByName<TextBox>("txtNotes")); }
            set { _txtCompNotes = value; }
        }
        private Button _btnSave = null;
        public Button btnSave
        {
            get { return _btnSave ?? (_btnSave = HWND.FindChildByName<Button>("btnSave")); }
            set { _btnSave = value; }
        }
        private Button _btnCreate = null;
        public Button btnCreate
        {
            get { return _btnCreate ?? (_btnCreate = HWND.FindChildByName<Button>("btnCreate")); }
            set { _btnCreate = value; }
        }
    }
}
