using RecruiterCRM.classes.Views.Helpers;
using RecruiterCRM.classes.Views;
using RecruiterCRM.classes;
using ConsoleFramework;
using ConsoleFramework.Controls;

namespace RecruiterCRM.forms
{
    /*
     *  GENERATED BY A YET-TO-BE-RELEASED CONSOLE EDITOR
     */
    [CRMFormTemplate("leads-list")]
    public partial class LeadsList
    {
        public LeadsList(CRM crm, CRMFormLanguage lang) : base(crm, lang) { }
        /*
         *  CONTROLS
         */
    }
}
