using RecruiterCRM.classes.Views.Helpers;
using RecruiterCRM.classes.Views;
using RecruiterCRM.classes;
using ConsoleFramework;
using ConsoleFramework.Controls;

namespace RecruiterCRM.forms
{
    /*
     *  GENERATED BY A YET-TO-BE-RELEASED CONSOLE EDITOR
     */
    [CRMFormTemplate("recruiters-list")]
    public partial class RecruitersList
    {
        public RecruitersList(CRM crm, CRMFormLanguage lang) : base(crm, lang) { }
        /*
         *  CONTROLS
         */
        private Panel _pnlRecruiter = null;
        public Panel pnlRecruiter
        {
            get { return _pnlRecruiter ?? (_pnlRecruiter = HWND.FindChildByName<Panel>("pnlRecruiter")); }
            set { _pnlRecruiter = value; }
        }
        private Button _btnCompanies = null;
        public Button btnCompanies
        {
            get { return _btnCompanies ?? (_btnCompanies = pnlRecruiter.FindChildByName<Button>("btnCompanies")); }
            set { _btnCompanies = value; }
        }
        private TextBox _txtName = null;
        public TextBox txtName
        {
            get { return _txtName ?? (_txtName = pnlRecruiter.FindChildByName<TextBox>("txtName")); }
            set { _txtName = value; }
        }
        private TextBox _txtEmail = null;
        public TextBox txtEmail
        {
            get { return _txtEmail ?? (_txtEmail = pnlRecruiter.FindChildByName<TextBox>("txtEmail")); }
            set { _txtEmail = value; }
        }
        private TextBox _txtTelephone = null;
        public TextBox txtTelephone
        {
            get { return _txtTelephone ?? (_txtTelephone = pnlRecruiter.FindChildByName<TextBox>("txtTelephone")); }
            set { _txtTelephone = value; }
        }
        private TextBox _txtFirstContact = null;
        public TextBox txtFirstContact
        {
            get { return _txtFirstContact ?? (_txtFirstContact = pnlRecruiter.FindChildByName<TextBox>("txtFirstContact")); }
            set { _txtFirstContact = value; }
        }
        private TextBox _txtNotes = null;
        public TextBox txtNotes
        {
            get { return _txtNotes ?? (_txtNotes = pnlRecruiter.FindChildByName<TextBox>("txtNotes")); }
            set { _txtNotes = value; }
        }
        private ComboBox _cmbCompanies = null;
        public ComboBox cmbCompanies
        {
            get { return _cmbCompanies ?? (_cmbCompanies = pnlRecruiter.FindChildByName<ComboBox>("cmbCompanies")); }
            set { _cmbCompanies = value; }
        }
        private ListBox _lstRecruiters = null;
        public ListBox lstRecruiters
        {
            get { return _lstRecruiters ?? (_lstRecruiters = HWND.FindChildByName<ListBox>("lstRecruiters")); }
            set { _lstRecruiters = value; }
        }
        private Button _btnSave = null;
        public Button btnSave
        {
            get { return _btnSave ?? (_btnSave = HWND.FindChildByName<Button>("btnSave")); }
            set { _btnSave = value; }
        }
        private Button _btnCreate = null;
        public Button btnCreate
        {
            get { return _btnCreate ?? (_btnCreate = HWND.FindChildByName<Button>("btnCreate")); }
            set { _btnCreate = value; }
        }
    }
}
