using RecruiterCRM.classes.Views.Helpers;
using RecruiterCRM.classes.Views;
using RecruiterCRM.classes;
using ConsoleFramework;
using ConsoleFramework.Controls;

namespace RecruiterCRM.forms
{
    /*
     *  GENERATED BY A YET-TO-BE-RELEASED CONSOLE EDITOR
     */
    [CRMFormTemplate("recruiters-search")]
    public partial class RecruitersSearch : CRMForm
    {
        public RecruitersSearch(CRM crm, CRMFormLanguage lang) : base(crm, lang) { }
        /*
         *  CONTROLS
         */
        private ListBox _lstResults = null;
        public ListBox lstResults
        {
            get { return _lstResults ?? (_lstResults = HWND.FindChildByName<ListBox>("lstResults")); }
            set { _lstResults = value; }
        }

        private TextBox _txtSearch = null;
        public TextBox txtSearch
        {
            get { return _txtSearch ?? (_txtSearch = HWND.FindChildByName<TextBox>("txtSearch")); }
            set { _txtSearch = value; }
        }
        private Button _btnGoto = null;
        public Button btnGoto
        {
            get { return _btnGoto ?? (_btnGoto = HWND.FindChildByName<Button>("btnGoto")); }
            set { _btnGoto = value; }
        }
        private Panel _pnlSearch = null;
        public Panel pnlSearch
        {
            get { return _pnlSearch ?? (_pnlSearch = HWND.FindChildByName<Panel>("pnlSearch")); }
            set { _pnlSearch = value; }
        }
        private Button _btnClose = null;
        public Button btnClose
        {
            get { return _btnClose ?? (_btnClose = pnlSearch.FindChildByName<Button>("btnClose")); }
            set { _btnClose = value; }
        }
    }
}
